import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { ToolError, assertInsideRoot } from '@harness/shared';
import { contentTag, documentTextPath, outRoot } from './layout.js';
import type { Storage, WriteFileInput, WrittenFile } from './types.js';

/**
 * Turn a caller-supplied path into an absolute path that is provably inside
 * `storageDir`. The agent chooses this string, so it is untrusted: without the
 * containment check, `documents_ingest` would read any file the process can.
 *
 * Checks both the lexical path and its real (symlink-resolved) path: a
 * symlink that lexically sits under `storageDir` but points outside it must
 * still be refused, or reading/hashing it would leak a file the containment
 * check was meant to block.
 */
export async function resolveStoragePath(storageDir: string, requested: string): Promise<string> {
  if (requested.trim() === '') throw new ToolError('document path is empty');
  return assertInsideRoot(requested, storageDir, () => {
    throw new ToolError('document path is outside HARNESS_STORAGE_DIR');
  });
}

/**
 * Turn a caller-supplied file id into an absolute path inside the out tree, or
 * refuse. A file id reaches us from a model, so an absolute path, a `..`
 * segment or an empty string is rejected rather than normalised away.
 *
 * The lexical check is not enough on its own: a symlink planted under the out
 * tree lexically resolves inside it, and both `stat` in `forms_release` and
 * `readFile` in the host's file sink follow symlinks, so the target would be
 * uploaded. The real paths are compared as well.
 */
export async function resolveOutFile(fileId: string, root: string): Promise<string> {
  if (fileId.trim() === '' || path.isAbsolute(fileId)) {
    throw new ToolError(`file id "${fileId}" must be a path relative to the output directory`);
  }
  return assertInsideRoot(
    fileId,
    outRoot(root),
    () => {
      throw new ToolError(`file id "${fileId}" is outside the output directory`);
    },
    // The out tree itself is not a file id.
    { allowRoot: false },
  );
}

export async function readDocumentBytes(absPath: string): Promise<Uint8Array> {
  try {
    return new Uint8Array(await readFile(absPath));
  } catch {
    // The path is caller-supplied and already validated, so naming it is safe;
    // the underlying errno message is not repeated.
    throw new ToolError(`cannot read document at ${absPath}`);
  }
}

export async function sha256File(absPath: string): Promise<string> {
  const bytes = await readDocumentBytes(absPath);
  return createHash('sha256').update(bytes).digest('hex');
}

/**
 * Write generated bytes to `out/<dir>/<name>-<contentTag>.<ext>`. The name is
 * content-addressed on purpose: regenerating identical content reuses the id,
 * so the `forms_release` that follows is idempotent for free, while changed
 * content gets a new id and can be released again.
 */
export async function writeOutFile(input: WriteFileInput, root: string): Promise<WrittenFile> {
  const fileId = `${input.dir}/${input.name}-${contentTag(input.bytes)}.${input.ext}`;
  const abs = await resolveOutFile(fileId, root);
  await mkdir(path.dirname(abs), { recursive: true });
  await writeFile(abs, input.bytes);
  return { file_id: fileId, path: abs, bytes: input.bytes.byteLength };
}

/**
 * The production `Storage`. A thin binding of the free functions above to one root, so a
 * caller holds an object instead of threading `deps.storageDir` through every call, and so a
 * test can hand a domain a stub without a filesystem.
 */
export function fileStorage(root: string): Storage {
  return {
    resolveIncoming: (requested) => resolveStoragePath(root, requested),
    resolveOut: (fileId) => resolveOutFile(fileId, root),
    read: (absPath) => readDocumentBytes(absPath),
    write: (input) => writeOutFile(input, root),
    textPathFor: (absPath) => documentTextPath(absPath),
  };
}
