import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { ToolError } from './registry.js';

/**
 * Root of the harness file store. There is no default: a deployment that has
 * not said where files live must fail at startup rather than scatter provider
 * documents into whatever directory happened to be the working directory.
 */
export function storageRoot(dir: string | undefined = process.env.HARNESS_STORAGE_DIR): string {
  if (!dir || dir.trim() === '') throw new Error('HARNESS_STORAGE_DIR must be set to an absolute path');
  return path.resolve(dir);
}

/**
 * Everything a human may receive lives under one subtree, so one guard covers
 * all of it and nothing a tool generates can land next to ingested documents.
 */
export function outRoot(root: string): string {
  return path.join(root, 'out');
}

/** First 12 hex of sha256: enough to make a file id content-addressed and stable. */
export function contentTag(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex').slice(0, 12);
}

/**
 * Turn a caller-supplied file id into an absolute path inside the out tree, or
 * refuse. A file id reaches us from a model, so an absolute path, a `..`
 * segment or an empty string is rejected rather than normalised away.
 */
export function resolveOutFile(fileId: string, root: string): string {
  const base = outRoot(root);
  if (fileId.trim() === '' || path.isAbsolute(fileId)) {
    throw new ToolError(`file id "${fileId}" must be a path relative to the output directory`);
  }
  const abs = path.resolve(base, fileId);
  const rel = path.relative(base, abs);
  if (rel === '' || rel === '..' || rel.startsWith(`..${path.sep}`) || path.isAbsolute(rel)) {
    throw new ToolError(`file id "${fileId}" is outside the output directory`);
  }
  return abs;
}

export interface WrittenFile {
  file_id: string;
  path: string;
  bytes: number;
}

/**
 * Write generated bytes to `out/<dir>/<name>-<contentTag>.<ext>`. The name is
 * content-addressed on purpose: regenerating identical content reuses the id,
 * so the `forms_release` that follows is idempotent for free, while changed
 * content gets a new id and can be released again.
 */
export async function writeOutFile(
  input: { dir: string; name: string; ext: string; bytes: Uint8Array },
  root: string,
): Promise<WrittenFile> {
  const fileId = `${input.dir}/${input.name}-${contentTag(input.bytes)}.${input.ext}`;
  const abs = resolveOutFile(fileId, root);
  await mkdir(path.dirname(abs), { recursive: true });
  await writeFile(abs, input.bytes);
  return { file_id: fileId, path: abs, bytes: input.bytes.byteLength };
}
